name: wechat_camera_picker_plus
description: A camera picker based on WeChat's UI which is a separate runnable extension to wechat_assets_picker.
version: 1.0.1
homepage: https://github.com/deepak07082/wechat_camera_picker_plus.git
repository: https://github.com/deepak07082/wechat_camera_picker_plus.git
issue_tracker: https://github.com/deepak07082/wechat_camera_picker_plus/issues

topics:
  - assets
  - wechat

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.2
  camera_platform_interface: ^2.10.0
  collection: ^1.19.1
  meta: ^1.16.0
  path: ^1.9.1
  photo_manager: ^3.7.1
  uuid: ^4.5.1
  video_player: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
